#!/bin/bash

export SNMPCONFPATH=$HOME/.snmp/write

network=(172.18.20.1 172.18.20.4 172.18.20.2 172.18.20.3)
#hide=(169.254.69.1 169.254.69.4 169.254.69.2 169.254.69.3)
hide=(172.18.20.1 172.18.20.4 172.18.20.2 172.18.20.3)

for i in $(seq 0 $((${#network[@]}-1)));do
    scriptIndex=$(snmpwalk ${network[$i]} .1.3.6.1.4.1.14988.1.1.8 |
    awk '$NF=="\"checkospfadj\""{print a[split($1,a,".")]}')
    snmpget ${network[$i]} .1.3.6.1.4.1.14988.1.1.18.1.1.2.${scriptIndex} |tr '\r' ' '|egrep -v '^ *$|^"$'|
    awk '{k=match($0,"STRING: \"");if(k){t=substr($0,k+9);}else{t=$0};print "'${hide[$i]}'",t}'
done
